import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Performance",
    description: "Generated by create next app",
};

export default function page() {
  return (
    <div className='text-green-500'>
      performance
    </div>
  )
}
