import type { Metadata } from "next";
import {Comforter} from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
};

const comforter =Comforter({
    subsets:['latin'],
    weight:'400',
    display:'swap'
})

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html >
            <body className={comforter.className}>
                {children}
            </body>
        </html>
    );
}
