import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Scale",
    description: "Generated by create next app",
};

export default function page() {
  return (
    <div className='text-blue-300'>
      scale
    </div>
  )
}
