import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata  = {
    title: "Reliability",
    description: "Generated by create next app",
};

export default function page() {
  return (
    <div className='text-purple-500'>
      reliability
    </div>
  )
}
